export const FETCH_DASHBOARD_LOADING = "FETCH_DASHBOARD_LOADING";
export const FETCH_DASHBOARD_FULFILLED = "FETCH_DASHBOARD_FULFILLED";
export const FETCH_DASHBOARD_ERROR = "FETCH_DASHBOARD_ERROR";

export const FETCH_ACCOUNT_LOADING = "FETCH_ACCOUNT_LOADING";
export const FETCH_ACCOUNT_FULFILLED = "FETCH_ACCOUNT_FULFILLED";
export const FETCH_ACCOUNT_ERROR = "FETCH_ACCOUNT_ERROR";
