export const FETCH_DASHBOARD_LOADING = "FETCH_DASHBOARD_LOADING";
export const FETCH_DASHBOARD_FULFILLED = "FETCH_DASHBOARD_FULFILLED";
export const FETCH_DASHBOARD_ERROR = "FETCH_DASHBOARD_ERROR";

export const FETCH_ACCOUNT_LOADING = "FETCH_ACCOUNT_LOADING";
export const FETCH_TOTAL_VALUE_LOADING = "FETCH_TOTAL_VALUE_LOADING";
export const FETCH_TOTAL_VALUE_FULFILLED = "FETCH_TOTAL_VALUE_FULFILLED";
export const FETCH_ACCOUNT_FULFILLED = "FETCH_ACCOUNT_FULFILLED";
export const FETCH_ACCOUNT_ERROR = "FETCH_ACCOUNT_ERROR";

export const FETCH_TYPES_OCCURRENCES_LOADING =
  "FETCH_TYPES_OCCURRENCES_LOADING";
export const FETCH_TYPES_OCCURRENCES_FULFILLED =
  "FETCH_TYPES_OCCURRENCES_FULFILLED";
export const FETCH_TYPES_OCCURRENCES_ERROR = "FETCH_TYPES_OCCURRENCES_ERROR";

export const FETCH_CATEGORIES_LOADING = "FETCH_CATEGORIES_LOADING";
export const FETCH_CATEGORIES_FULFILLED = "FETCH_CATEGORIES_FULFILLED";
export const FETCH_CATEGORIES_ERROR = "FETCH_CATEGORIES_ERROR";

export const REQUEST_OCCURRENCE_INCOME_LOADING =
  "REQUEST_OCCURRENCE_INCOME_LOADING";
export const REQUEST_OCCURRENCE_TRANSFERENCE_LOADING =
  "REQUEST_OCCURRENCE_TRANSFERENCE_LOADING";
export const REQUEST_OCCURRENCE_EXPENSE_LOADING =
  "REQUEST_OCCURRENCE_EXPENSE_LOADING";
export const FETCH_OCCURRENCES_LOADING = "FETCH_OCCURRENCES_LOADING";
export const REQUEST_OCCURRENCES_FULFILLED = "REQUEST_OCCURRENCES_FULFILLED";
export const REQUEST_OCCURRENCES_ERROR = "REQUEST_OCCURRENCES_ERROR";
export const DELETE_OCCURRENCE = "DELETE_OCCURRENCE";
export const DELETE_OCCURRENCE_SUCCESS = "DELETE_OCCURRENCE_SUCCESS";
